package ru.job4j.cars.model.repository;

import org.springframework.stereotype.Repository;
import ru.job4j.cars.model.CarMarc;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Хранилище с информацией об марках автомобилей в ОЗУ
 */
@Repository
public class CarMarcMemRepository implements CarMarcAbstractRepository {
    private static final List<String> MARC_NAMES = List.of(
            "AC",
            "Acura",
            "Adler",
            "Aito",
            "Alfa Romeo",
            "Alpina",
            "Alpine",
            "AM General",
            "AMC",
            "Apal",
            "Arcfox",
            "Ariel",
            "Aro",
            "Asia",
            "Aston Martin",
            "Auburn",
            "Audi",
            "Aurus",
            "Austin",
            "Austin Healey",
            "Auto Union",
            "Autobianchi",
            "BAIC",
            "Bajaj",
            "Baltijas Dzips",
            "Baojun",
            "Batmobile",
            "Bentley",
            "Bertone",
            "Bilenkin",
            "Bio auto",
            "Bitter",
            "Blaval",
            "BMW",
            "Borgward",
            "Brabus",
            "Brilliance",
            "Bristol",
            "Bufori",
            "Bugatti",
            "Buick",
            "BYD",
            "Byvin",
            "Cadillac",
            "Callaway",
            "Carbodies",
            "Caterham",
            "Chana",
            "Changan",
            "ChangFeng",
            "Changhe",
            "Chery",
            "Chevrolet",
            "Chrysler",
            "Ciimo (DongFeng-Honda)",
            "Citroen",
            "Cizeta",
            "Coggiola",
            "Cord",
            "Cupra",
            "Dacia",
            "Dadi",
            "Daewoo",
            "Daihatsu",
            "Daimler",
            "Dallara",
            "Datsun",
            "De Tomaso",
            "Deco Rides",
            "Delage",
            "DeLorean",
            "Denza",
            "Derways",
            "DeSoto",
            "DKW",
            "Dodge",
            "DongFen",
            "Doninvest",
            "Donkervoort",
            "DS",
            "DW Hower",
            "E-Car",
            "Eagle",
            "Eagle Cars",
            "Everus",
            "Evolute",
            "Excalibur",
            "EXEED",
            "Facel Vega",
            "FAW",
            "Ferrari",
            "Fiat",
            "Fisker",
            "Flanker",
            "Ford",
            "Foton",
            "FSO",
            "Fuqi",
            "GAC",
            "GAC Aion",
            "Geely",
            "Genesis",
            "Geo",
            "GMC",
            "Goggomobil",
            "Gonow",
            "Gordon",
            "GP",
            "Great Wall",
            "Hafei",
            "Haima",
            "Hanomag",
            "Haval",
            "Hawtai",
            "Heinkel",
            "Hennessey",
            "Hindustan",
            "HiPhi",
            "Hispano-Suiza",
            "Holden",
            "Honda",
            "Hongqi",
            "Horch",
            "Hozon",
            "HSV",
            "HuangHai",
            "Hudson",
            "Hummer",
            "Hyundai",
            "Infiniti",
            "Innocenti",
            "International",
            "Invicta",
            "Iran Khodro",
            "Isdera",
            "Isuzu",
            "IVECO",
            "JAC",
            "Jaguar",
            "Jeep",
            "Jensen",
            "Jetour",
            "Jetta",
            "Jinbei",
            "JMC",
            "Kaiyi",
            "Kia",
            "Koenigsegg",
            "KTM AG",
            "LADA (ВАЗ)",
            "Lamborghini",
            "Lancia",
            "Land Rover",
            "Landwind",
            "Leapmotor",
            "Lexus",
            "Liebao Motor",
            "Lifan",
            "Ligier",
            "Lincoln",
            "LiXiang",
            "Logem",
            "Lotus",
            "LTI",
            "Lucid",
            "Luxgen",
            "Lynk & Co",
            "Mahindra",
            "Marcos",
            "Marlin",
            "Marussia",
            "Maruti",
            "Maserati",
            "Matra",
            "Maybach",
            "Mazda",
            "McLaren",
            "Mega",
            "Mercedes-Benz",
            "Mercury",
            "Messerschmitt",
            "Metrocab",
            "MG",
            "Microcar",
            "Minelli",
            "MINI",
            "Mitsubishi",
            "Mitsuoka",
            "Mobilize",
            "Morgan",
            "Morris",
            "Nash",
            "Nio",
            "Nissan",
            "Noble",
            "Oldsmobile",
            "OMODA",
            "Opel",
            "ORA",
            "Osca",
            "Oshan",
            "Packard",
            "Pagani",
            "Panoz",
            "Perodua",
            "Peugeot",
            "PGO",
            "Piaggio",
            "Pierce-Arrow",
            "Plymouth",
            "Polestar",
            "Pontiac",
            "Porsche",
            "Premier",
            "Proton",
            "PUCH",
            "Puma",
            "Qoros",
            "Qvale",
            "RAM",
            "Ravon",
            "Reliant",
            "Renaissance",
            "Renault",
            "Renault Samsung",
            "Rezvani",
            "Rimac",
            "Rinspeed",
            "Rivian",
            "Roewe",
            "Rolls-Royce",
            "Ronart",
            "Rover",
            "Saab",
            "Saipa",
            "Saleen",
            "Santana",
            "Saturn",
            "Scion",
            "Sears",
            "SEAT",
            "Seres",
            "Shanghai Maple",
            "ShuangHuan",
            "Simca",
            "Skoda",
            "Skywell",
            "Smart",
            "Soueast",
            "Spectre",
            "Spyker",
            "SsangYong",
            "Steyr",
            "Studebaker",
            "Subaru",
            "Suzuki",
            "Talbot",
            "Tank",
            "TATA",
            "Tatra",
            "Tazzari",
            "Tesla",
            "Think",
            "Tianma",
            "Tianye",
            "Tofas",
            "Toyota",
            "Trabant",
            "Tramontana",
            "Triumph",
            "Trumpchi",
            "TVR",
            "Ultima",
            "Vauxhall",
            "Vector",
            "Venturi",
            "Volkswagen",
            "Volvo",
            "Vortex",
            "Voyah",
            "VUHL",
            "W Motors",
            "Wanderer",
            "Wartburg",
            "Weltmeister",
            "Westfield",
            "WEY",
            "Wiesmann",
            "Willys",
            "Xin Kai",
            "Xpeng",
            "Yulon",
            "Zastava",
            "Zeekr",
            "Zenos",
            "Zenvo",
            "Zibar",
            "Zotye",
            "ZX",
            "Автокам",
            "ГАЗ",
            "ЗАЗ",
            "ЗИЛ",
            "ЗиС",
            "ИЖ",
            "Канонир",
            "Комбат",
            "ЛуАЗ",
            "Москвич",
            "СМЗ",
            "Спортивные авто и Реплики",
            "ТагАЗ",
            "УАЗ",
            "Ё-мобиль"
    );

    private final Map<Integer, CarMarc> marcs = new ConcurrentHashMap<>();

    public CarMarcMemRepository() {
        MARC_NAMES.forEach(
                name -> {
                    int index = marcs.size() + 1;
                    CarMarc carMarc = new CarMarc();
                    carMarc.setId(index);
                    carMarc.setName(name);
                    marcs.putIfAbsent(index, carMarc);
                }
        );
    }

    /**
     * Список авто марок отсортированных по id.
     * @return список авто марок.
     */
    public List<CarMarc> findAll() {
        return marcs.values().stream().toList();
    }

    /**
     * Найти авто марку по ID
     * @param id идентификотор авто марки
     * @return авто марка.
     */
    public Optional<CarMarc> findById(int id) {
        return Optional.ofNullable(marcs.getOrDefault(id, null));
    }

    /**
     * Найти авто марку по имени
     * @param name имя авто марки
     * @return ID авто марки, 0 если нет такого имени.
     */
    public int findIdByName(String name) {
        return marcs.values()
                .stream()
                .filter(marc -> marc.getName().equals(name))
                .findFirst()
                .orElse(new CarMarc())
                .getId();
    }

}
